/* ============================================================
   LISTADOS MAESTROS (desplegables de las planillas)
   ------------------------------------------------------------
   Esto es lo que en el Excel eran las hojas "Listado de...".
   Para actualizar (alta/baja de personal u obras) editá ESTE
   archivo y subí el cambio. No hace falta tocar el resto.
   ============================================================ */

const LISTADOS = {

  // [Supervisor, Ubicación, Taller]
  supervisores: [
    ["Deheza Daniel",  "Base 4",     "Pesado"],
    ["Sanchez Matías", "Base 4",     "Liviano"],
    ["Segura Pablo",   "Base 4",     "Estacionario"],
    ["Garcia Lucas",   "Base 4",     "Vial y Carretones"],
    ["Lera Ezequiel",  "Zona Norte", "Campo"],
    ["Sepulveda Luis", "Zona Sur",   "Campo"],
    ["Roger Melo",     "Base 4",     "Noche"],
  ],

  // [Semana, Desde, Hasta]
  semanas: [
    ["Semana 1",  "10/5/2026",  "16/5/2026"],
    ["Semana 2",  "17/5/2026",  "23/5/2026"],
    ["Semana 3",  "24/5/2026",  "30/5/2026"],
    ["Semana 4",  "31/5/2026",  "6/6/2026"],
    ["Semana 5",  "7/6/2026",   "13/6/2026"],
    ["Semana 6",  "14/6/2026",  "20/6/2026"],
    ["Semana 7",  "21/6/2026",  "27/6/2026"],
    ["Semana 8",  "28/6/2026",  "4/7/2026"],
    ["Semana 9",  "5/7/2026",   "11/7/2026"],
    ["Semana 10", "12/7/2026",  "18/7/2026"],
    ["Semana 11", "19/7/2026",  "25/7/2026"],
    ["Semana 12", "26/7/2026",  "1/8/2026"],
    ["Semana 13", "2/8/2026",   "8/8/2026"],
    ["Semana 14", "9/8/2026",   "15/8/2026"],
    ["Semana 15", "16/8/2026",  "22/8/2026"],
    ["Semana 16", "23/8/2026",  "29/8/2026"],
    ["Semana 17", "30/8/2026",  "5/9/2026"],
    ["Semana 18", "6/9/2026",   "12/9/2026"],
    ["Semana 19", "13/9/2026",  "19/9/2026"],
    ["Semana 20", "20/9/2026",  "26/9/2026"],
    ["Semana 21", "27/9/2026",  "3/10/2026"],
    ["Semana 22", "4/10/2026",  "10/10/2026"],
    ["Semana 23", "11/10/2026", "17/10/2026"],
    ["Semana 24", "18/10/2026", "24/10/2026"],
  ],

  // [Ubicación, Obra]
  obras: [
    ["Base 4",     "Base 4"],
    ["Zona Sur",   "Base 7"],
    ["Zona Norte", "Bases 2,3, 5 y 10"],
    ["Zona Sur",   "352-Chacras"],
    ["Zona Norte", "475"],
    ["Zona Norte", "689"],
    ["Zona Norte", "703"],
    ["Zona Sur",   "706"],
    ["Zona Norte", "708"],
    ["Zona Norte", "710"],
    ["Zona Norte", "711"],
    ["Zona Sur",   "715"],
    ["Zona Norte", "719"],
    ["Zona Norte", "720"],
    ["Zona Norte", "721"],
    ["Zona Norte", "723"],
    ["Zona Norte", "725"],
    ["Zona Norte", "726"],
    ["Zona Norte", "727"],
    ["Zona Norte", "738"],
    ["Zona Norte", "745"],
    ["Zona Norte", "746"],
    ["Zona Norte", "747"],
    ["Zona Norte", "755"],
    ["Zona Norte", "756"],
    ["Zona Norte", "757"],
    ["Zona Sur",   "758"],
    ["Zona Norte", "759"],
    ["Zona Sur",   "760"],
    ["Zona Norte", "762"],
    ["Zona Norte", "763"],
    ["Zona Norte", "764"],
    ["Zona Norte", "766"],
    ["Zona Sur",   "767"],
    ["Zona Norte", "770"],
    ["Zona Norte", "771"],
    ["Zona Norte", "772"],
    ["Zona Norte", "773"],
    ["Zona Norte", "777"],
    ["Zona Norte", "779"],
  ],

  // [Nombre, Ubicación, Taller]  (para futuras planillas)
  mecanicos: [
    ["Montes Moises", "Base 4", "Liviano"],
    ["Bustamante Martin", "Base 4", "Liviano"],
    ["Sosa Pablo", "Base 4", "Liviano"],
    ["Bazcur Franco", "Base 4", "Pesado"],
    ["Jara Yonathan", "Base 4", "Liviano"],
    ["Montecinos Emanuel", "Base 4", "Liviano"],
    ["Acuña Gonzalo", "Base 4", "Liviano"],
    ["Sura Agustin", "Base 4", "Liviano"],
    ["Varde Agustin", "Base 4", "Liviano"],
    ["Garrido Angel", "Base 4", "Liviano"],
    ["Briceño Oscar", "Base 4", "Pesado"],
    ["Gutierrez Facundo", "Base 4", "Pesado"],
    ["Burgos Alexis", "Base 4", "Pesado"],
    ["Pires Da Sil Andres", "Base 4", "Pesado"],
    ["Waltemath Emiliano", "Base 4", "Pesado"],
    ["Fuentealba Jorge", "Base 4", "Pesado"],
    ["Arancibia Rodrigo", "Base 4", "Pesado"],
    ["Cruz Sergio", "Base 4", "Pesado"],
    ["Toledo Carlos", "Base 4", "Vial y Carretones"],
    ["Mora Miguel Angel", "Base 4", "Vial y Carretones"],
    ["Gimenez Lucas", "Base 4", "Vial y Carretones"],
    ["Gimenez Nicolas", "Base 4", "Vial y Carretones"],
    ["Lopez Walter", "Base 4", "Vial y Carretones"],
    ["Betancur Alexis", "Base 4", "Estacionario"],
    ["Huenchupan Abel", "Base 4", "Estacionario"],
    ["Peña Ignacio Victor", "Base 4", "Estacionario"],
    ["Castillo Manuel", "Base 4", "Estacionario"],
    ["Quiroga Mauro", "Base 4", "Noche"],
    ["Cardozo Julio Cesar", "Base 4", "Noche"],
    ["Groppa Facundo", "Base 4", "Noche"],
    ["Zelada Jose Jorge", "Base 4", "Noche"],
    ["Garcia Lucas Tomas", "Base 4", "Noche"],
    ["Orellana Jose", "Zona Norte", "Campo"],
    ["Taladriz David", "Zona Norte", "Campo"],
    ["Sandoval Roy", "Zona Norte", "Campo"],
    ["Bogado Lucas", "Zona Norte", "Campo"],
    ["Molina Lucas", "Zona Norte", "Campo"],
    ["Lera Kevin", "Zona Norte", "Campo"],
    ["Sepulveda Matias", "Zona Norte", "Campo"],
    ["Cavo Braian", "Zona Norte", "Campo"],
    ["Muñoz Juan Carlos", "Zona Norte", "Campo"],
    ["Ghio Julian", "Zona Norte", "Campo"],
    ["Molina Mauricio", "Zona Norte", "Campo"],
    ["Caraballo Daniel", "Zona Norte", "Campo"],
    ["Bello Pablo Matias", "Zona Norte", "Campo"],
    ["Cid Braian", "Zona Sur", "Campo"],
    ["Kette Martin", "Zona Sur", "Campo"],
    ["Bravo Nahuel", "Zona Sur", "Campo"],
    ["Antolinez Lucas", "Zona Sur", "Campo"],
    ["Cardenas Walter", "Zona Sur", "Campo"],
    ["Banegas Emanuel", "Zona Sur", "Campo"],
    ["Maldonado Ricardo", "Zona Sur", "Campo"],
    ["Gonzalez Lucas", "Zona Sur", "Campo"],
    ["Lopez Fernando Sebastian", "Zona Sur", "Campo"],
    ["Guaimas Eduardo David", "Zona Sur", "Campo"],
  ],

  // [Nombre, Ubicación, Pañol]  (para futuras planillas)
  panoleros: [
    ["Fuentealba Miguel", "Base 4", "Central"],
    ["Romero Nahuel", "Base 4", "Central"],
    ["Quintana Tomas", "Base 4", "Central"],
    ["Lucero Matias", "Base 4", "Central"],
    ["Pedernera Iván Eric", "Base 4", "Central"],
    ["Declerico Franco", "Base 4", "M"],
    ["Canario Luciano", "Base 4", "M"],
    ["Rebaliati Andrés", "Base 4", "M"],
    ["Bustamante Nicolas", "Base 4", "Estacionario"],
    ["Choquevilca Maximiliano", "760", "Campo"],
    ["Alegre Maximiliano", "758", "Campo"],
    ["Garces Agustin", "Base 4", ""],
  ],

  // Tipos de taller (para filtros)
  talleres: ["Pesado", "Liviano", "Estacionario", "Vial y Carretones", "Campo", "Noche"],
};
